server.port=${HRMS_SERVER_PORT}
server.servlet.context-path=${HRMS_CONTEXT_PATH}
spring.datasource.url=${HRMS_DB_URL}
spring.datasource.username=${HRMS_DB_USERNAME}
spring.datasource.password=${HRMS_DB_PASSWORD}
spring.datasource.hikari.schema=${HRMS_DB_SCHEMA}
spring.jpa.properties.hibernate.default_schema=${HRMS_HIBERNATE_SCHEMA}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
springdoc.api-docs.path=/api-docs